-- MySQL Script generated by MySQL Workbench
-- Fri Oct 19 20:21:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Marktred
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Marktred` ;

-- -----------------------------------------------------
-- Schema Marktred
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Marktred` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Marktred` ;

-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Category` (
  `idCategory` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Commentary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Commentary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Commentary` (
  `User_idUser` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `Products_Category_idCategory` INT NOT NULL,
  `IDCommentary` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Products_idProducts`, `Products_Category_idCategory`, `IDCommentary`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `History` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `History` (
  `User_idUser` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `Products_Category_idCategory` INT NOT NULL,
  `Products_User_idUser` INT NOT NULL,
  `idHistory` INT NOT NULL,
  `Status` BIT(0) NULL,
  PRIMARY KEY (`User_idUser`, `Products_idProducts`, `Products_Category_idCategory`, `Products_User_idUser`, `idHistory`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Products` (
  `idProducts` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Description` VARCHAR(500) NULL,
  `Category` VARCHAR(50) NULL,
  `Prize` INT NULL,
  `Units` INT NULL,
  `firstImage` BLOB NULL,
  `secondImage` BLOB NULL,
  `thirdImage` BLOB NULL,
  `video` BLOB NULL,
  `Category_idCategory` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Status` BIT(0) NULL,
  PRIMARY KEY (`idProducts`, `Category_idCategory`, `User_idUser`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShoppingCart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ShoppingCart` (
  `User_idUser` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `Products_Category_idCategory` INT NOT NULL,
  `idShoppingCart` INT NOT NULL,
  `Units` INT NULL,
  PRIMARY KEY (`User_idUser`, `Products_idProducts`, `Products_Category_idCategory`, `idShoppingCart`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `Username` VARCHAR(50) NULL,
  `Email` VARCHAR(50) NULL,
  `Phone` INT NULL,
  `Password` VARCHAR(50) NULL,
  `profileImage` VARCHAR(100) NULL,
  `bannerImage` VARCHAR(100) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
